### ISSUE TITLE
HA 2024.11.0 & ComfoConnect 0.3.0: errors!

### ISSUE THREAD

**Issue by ChrisMisker** [michaelarnauts/home-assistant-comfoconnect#94]
I installed all the new versions, but I still get these errors:
```
Logger: homeassistant.util.package
Source: util/package.py:78
First occurred: 12:03:19 (2 occurrences)
Last logged: 12:03:22

Installed version for aiocomfoconnect resolved to None
```

Warning:
```
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 12:03:36 (1 occurrences)
Last logged: 12:03:36

Detected blocking call to import_module with args ('custom_components.comfoconnect',) in /usr/src/homeassistant/homeassistant/loader.py, line 1071: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
```

Error:
```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 12:03:36 (1 occurrences)
Last logged: 12:03:36

Setup failed for custom integration 'comfoconnect': Unable to import component: cannot import name 'ComfoConnect' from 'aiocomfoconnect' (/usr/local/lib/python3.12/site-packages/aiocomfoconnect/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/comfoconnect/__init__.py", line 8, in <module>
    from aiocomfoconnect import ComfoConnect, discover_bridges
ImportError: cannot import name 'ComfoConnect' from 'aiocomfoconnect' (/usr/local/lib/python3.12/site-packages/aiocomfoconnect/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/comfoconnect/__init__.py", line 8, in <module>
    from aiocomfoconnect import ComfoConnect, discover_bridges
ImportError: cannot import name 'ComfoConnect' from 'aiocomfoconnect' (/usr/local/lib/python3.12/site-packages/aiocomfoconnect/__init__.py)
```

I have tried reinstalling 0.3.0, but didn't work. Tried downgrading, and then upgrading.. Tried removing and reading. Nothing worked. I've only not downgraded HA, I'm not looking forward to that. :P

**Comment by chheiss** [comment]
Same here. After upgrade of HA to 2024.11.0, Zehnder integration is not loading anymore. Error during startup.

**Comment by roelvdgun** [comment]
Same here. Went back to last version

**Comment by ChrisMisker** [comment]
Nope, that didn't work for me. I had already tried similar stuff, reinstalling 0.3.0 multiple times.

**Comment by joshburkard** [comment]
i had the same issue, that i tried multiple times to re-download with no success.

then i did:

- a restore of last vm backup
- re-applied 2024.11.0
- re-downloaded the ComfoConnect v0.3.0
- rebooted Home Assistant
- deleted all unavailable sensors from entities

now the sensors and controls were back again.

**Comment by ChrisMisker** [comment]
Is there any way to do this without going back to 2024.10.4?

**Comment by chheiss** [comment]
Well, for me it worked following bartwr comment.
