### ISSUE TITLE
Integration failling to load after HA upgrade to 2024.9.3

### ISSUE THREAD

**Issue by litinoveweedle** [michaelarnauts/home-assistant-comfoconnect#81]
Hello,

after upgrade of the HA to 2024.9.3 (from 2024.9.2) the latest integration versions v0.2.2 stops working with the log message:

```
2024-09-24 21:22:08.241 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.comfoconnect',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
2024-09-24 21:22:08.243 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'comfoconnect': Unable to import component: cannot import name 'runtime_version' from 'google.protobuf' (/usr/local/lib/python3.12/site-packages/google/protobuf/__init__.py)
File "/config/custom_components/comfoconnect/__init__.py", line 8, in <module>
from aiocomfoconnect import ComfoConnect, discover_bridges
File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/__init__.py", line 3, in <module>
File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 27, in <module>
File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/protobuf/zehnder_pb2.py", line 15, in <module>
File "/config/custom_components/comfoconnect/__init__.py", line 8, in <module>
from aiocomfoconnect import ComfoConnect, discover_bridges
File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/__init__.py", line 3, in <module>
File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 27, in <module>
File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/protobuf/zehnder_pb2.py", line 15, in <module>
```

**Comment by litinoveweedle** [comment]
related to #80 and #77
